apiVersion: v1
kind: Service
metadata:
    name: app-scale-s
    labels:
        app: app-scale
spec:
    type: NodePort
    selector:
        app: app-scale
    ports:
      - protocol: TCP
        port: 5000
        nodePort: 31110
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-scale-d
    labels:
        app: app-scale
spec:
    replicas: 4
    selector:
        matchLabels:
            app: app-scale
    minReadySeconds: 3
    template:
        metadata:
            labels:
                app: app-scale
        spec:
            containers:
              - name: app-scale
                image: app-scale
                imagePullPolicy: Never
                ports:
                  - containerPort: 5000
            
