apiVersion: v1
kind: Secret
metadata:
    name: user-pass-file
type: Opaque
data:
    username: "dXNlcm5hbWV2YWx1ZQo="
    password: "cGFzc3dvcmR2YWx1ZQo="
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-secret-d
    labels:
        app: app-secret
spec:
    selector:
        matchLabels:
            app: app-secret
    minReadySeconds: 3
    template:
        metadata:
            labels:
                app: app-secret
        spec:
            containers:
              - name: app-secret
                image: app_secret
                imagePullPolicy: Never
                env:
                  - name: USERNAME
                    valueFrom:
                        secretKeyRef:
                            name: user-pass-file
                            key: username
                  - name: PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: user-pass-file
                            key: password
                ports:
                  - containerPort: 5000
            
